apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: cloudchamp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend  # Name of your deployment (e.g., frontend or api)
  minReplicas: 1
  maxReplicas: 5  # Maximum number of replicas (adjust as needed)
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50  # Scale up when memory utilization exceeds 50%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20  # Scale down when memory utilization drops below 20%

